### ISSUE TITLE
Tabs and X/Y dimensions on some models

### ISSUE THREAD

**Issue by FurbsCA** [5axes/TabPlus#13]
I've had great success with your plug in, so thank you, but I came across a strange, reproducable issue last night.

When I add tabs, either manually or automatically, it changes the scaling in Cura (5.3.1)

![image](https://github.com/5axes/TabPlus/assets/110001321/0decbcba-e691-483b-8301-152a8ebb1b7e)

The scaling appears random, albeit I've only seen it between 100 and 105%. 
What I unfortunately discovered last night is this number is, I think wrong. I manually changed the settings back to 100% but after my print completed, its actually about 5% smaller than it should be. 

Looking at some of the other models I printed in the last couple of days with tabs added, they seem to be ok, so it seems model specific. I don't think its this particular file though - I've had this issue on other prints (from other creators) in the past, but they have not been pieces where I would have noticed a few millimeters or even a centimeter either way.

I would offer to send the model for you to test, but its a paid for STL - if you think this is a potential issue though, rather than me doing something stupid and need the model, I can ask the creator if I can send you it - its part of a larger model and they are very supportive of the print community so hopefully they would be open to it.

**Comment by 5axes** [comment]
I think , I already see this issue.But it's a Cura problem and I cannot do anything : 
When you add some tabs the model size change because the tabs increase the maximum dimension of the model+tabs . So Cura gives you the new percentage dimensions compare to the initial 100% value. But the real dimension doesn't change. As you can see on the Z value you still have 100% because the tabs doesn't change anything on Z. You certainly have the same issue if you use any other function like the custom support. My advice don't care about these values.

**Comment by FurbsCA** [comment]
That makes perfect sense, thank you for the explanation.
